/** All tunable numbers. Values from GAME_DESIGN, TECH and DESIGN_SYSTEM. */
export const TUNING = {
  breath: {
    presets: {
      normal: { inSeconds: 4, outSeconds: 4 },
      slow: { inSeconds: 5, outSeconds: 6 },
      easy: { inSeconds: 3, outSeconds: 3 },
    },
    /** An in-breath must last at least this long to count. */
    minInSeconds: 1,
    /** The out-breath is complete when the level falls to this. */
    emptyLevel: 0.05,
    /** Seconds of autobreathe in / out (debug). */
    autoIn: 1.4,
    autoOut: 1.1,
  },
  restless: {
    tauRise: 3,
    tauStill: 1.5,
    /** Angle change per second that counts as a sharp turn (rad/s). 90°/s. */
    turnThreshold: Math.PI / 2,
    /** Turn rate (rad/s) above threshold that maps to 1. */
    turnMax: Math.PI * 2,
    speedWeight: 0.6,
    turnWeight: 0.4,
  },
  disturb: {
    colliderRadius: 1.6,
    connectedRadius: 0.8,
    nearRange: 6,
    pushRange: 3.2,
    choiceRange: 4.2,
    leaveRange: 14,
    pushGrowth: 0.15,
    pushMax: 1.6,
    stepAside: 1.5,
    stepAsideSeconds: 2.5,
    connectedScale: 0.8,
    audibleRange: 25,
    pulseCalmHz: 0.4,
    pulseRestlessHz: 1.2,
    pulseConnectedHz: 0.25,
    emissiveMin: 0.15,
    emissiveMax: 0.45,
    emissiveConnected: 0.2,
    darkenRadius: 7,
  },
  player: {
    walkSpeed: 4.2,
    accel: 10,
    radius: 0.35,
    height: 1.6,
    chestLightStart: 0.35,
    chestLightStep: 0.22,
  },
  camera: {
    distance: 6.2,
    height: 2.6,
    lookHeight: 1.2,
    recentreDelay: 1.2,
    recentreSpeed: 2.0,
    dragSensitivity: 0.006,
    fov: 0.9,
    minPitch: -0.1,
    maxPitch: 0.85,
    pitch: 0.28,
  },
  inner: {
    gazeRest: 1.5,
    driftSpeed: 0.4,
    dragSensitivity: 0.005,
    heartSeconds: 10,
    oneBreaths: 3,
    stepSeconds: 2,
  },
  motion: {
    fadeIn: 400,
    fadeOut: 300,
    diveMin: 1.5,
    goldFade: 0.8,
    returnSeconds: 1.6,
    zoneGrow: 3,
  },
  world: {
    startSaturation: 0.08,
    zoneEdge: 2,
    zoneBrighten: 0.08,
    hazeStart: 18,
    hazeEnd: 150,
    zoneRadius: 7,
    maxZones: 8,
    walkCell: 0.5,
    laneWidth: 3,
  },
  echo: {
    maxFragments: 20,
    minWords: 3,
    maxWords: 6,
    showRange: 6,
    cooldown: 20,
    showSeconds: 5,
  },
  ai: {
    timeoutMs: 6000,
    questionMax: 140,
    chipMax: 28,
    chipsMin: 2,
    chipsMax: 6,
    textMax: 200,
  },
  hints: {
    walkFadeAfter: 5,
  },
  perf: {
    dprTouch: 1.5,
    dprDesktop: 2,
    adaptInterval: 2.5,
    lowFps: 38,
    highFps: 56,
    scaleMin: 1,
    scaleMax: 2.5,
    scaleStep: 0.25,
  },
  audio: {
    ambienceMin: 0.35,
    ambienceMax: 0.6,
    master: 0.8,
  },
} as const;

export type RhythmPreset = keyof typeof TUNING.breath.presets;
